CREATE TABLE IF NOT EXISTS FABRICANTE(
  ID_FABRICANTE SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME_FANTASIA VARCHAR(100) NOT NULL,
  RAZAO_SOCIAL VARCHAR(150) NOT NULL,
  CNPJ VARCHAR(14) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
  ID_CATEGORIA INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_CATEGORIA_PAI INTEGER REFERENCES CATEGORIA(ID_CATEGORIA),
  DESCRICAO VARCHAR(400)
);

CREATE TABLE IF NOT EXISTS PRODUTO (
  ID_PRODUTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CD_SKU VARCHAR(50) UNIQUE,
  CD_EAN VARCHAR(14) UNIQUE,
  NM_PRODUTO VARCHAR(250),
  DESCRICAO VARCHAR(1000),
  ID_FABRICANTE SMALLINT REFERENCES fabricante(ID_FABRICANTE),
  PRECO NUMERIC(15,2) NOT NULL CHECK (PRECO >= 0)
);

CREATE TABLE IF NOT EXISTS PRODUTO_IMAGEM(
  ID_PRODUTO_IMAGEM BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_PRODUTO BIGINT references produto(ID_PRODUTO) ON DELETE CASCADE,
  S3_CODE VARCHAR(1000),
  FL_DESTAQUE BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS CATEGORIA_PRODUTO(
  ID_CATEGORIA_PRODUTO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_PRODUTO BIGINT REFERENCES produto(ID_PRODUTO) ON DELETE CASCADE,
  ID_CATEGORIA INTEGER REFERENCES categoria(ID_CATEGORIA) ON DELETE CASCADE,
  UNIQUE(ID_PRODUTO, ID_CATEGORIA)
);






